import streamlit as st
import os
import math
from pydub import AudioSegment

def save_uploadedfile(uploadedfile, path):
    """Save uploaded file to a specified path."""
    with open(os.path.join(path, uploadedfile.name), "wb") as f:
        f.write(uploadedfile.getbuffer())
    return os.path.join(path, uploadedfile.name)

def apply_compression_to_all(uploaded_files, compression_ratio):
    """Apply compression to all uploaded tracks, considering overall balance."""
    compressed_files = {}
    for category, files in uploaded_files.items():
        compressed_category_files = []
        for file_path in files:
            audio = AudioSegment.from_file(file_path, format="wav")
            # Note: Pydub's compress_dynamic_range is a simplistic approach.
            compressed_audio = audio.compress_dynamic_range(threshold=compression_ratio)
            compressed_file_path = file_path.replace(".wav", "_compressed.wav")
            compressed_audio.export(compressed_file_path, format="wav")
            compressed_category_files.append(compressed_file_path)
        compressed_files[category] = compressed_category_files
    return compressed_files

def apply_volume_balancing(uploaded_files, volume_adjustments):
    """Adjust volume levels for clarity and balance across tracks."""
    balanced_files = {}
    for category, files in uploaded_files.items():
        balanced_category_files = []
        adjustment = volume_adjustments.get(category, 0)
        for file_path in files:
            audio = AudioSegment.from_file(file_path, format="wav")
            balanced_audio = audio + adjustment
            balanced_file_path = file_path.replace(".wav", "_balanced.wav")
            balanced_audio.export(balanced_file_path, format="wav")
            balanced_category_files.append(balanced_file_path)
        balanced_files[category] = balanced_category_files
    return balanced_files

def apply_equalization(uploaded_files, eq_settings, multi_pass_count=1):
    """
    Optimize frequencies for each track to avoid overlap and ensure clarity.
    Applies both a low-pass and high-pass filter.
    """
    eq_files = {}
    for category, files in uploaded_files.items():
        eq_category_files = []
        low_pass = eq_settings[category]['low_pass']
        high_pass = eq_settings[category]['high_pass']
        for file_path in files:
            audio = AudioSegment.from_file(file_path, format="wav")
            eq_audio = audio
            for _ in range(multi_pass_count):
                eq_audio = eq_audio.low_pass_filter(low_pass).high_pass_filter(high_pass)
            eq_file_path = file_path.replace(".wav", "_eq.wav")
            eq_audio.export(eq_file_path, format="wav")
            eq_category_files.append(eq_file_path)
        eq_files[category] = eq_category_files
    return eq_files

def apply_panning(uploaded_files, panning_settings):
    """
    Apply panning to position tracks in the stereo space.
    -1.0 = Full Left, 
     0.0 = Center, 
     1.0 = Full Right
    """
    panned_files = {}
    for category, files in uploaded_files.items():
        panned_category_files = []
        pan_value = panning_settings.get(category, 0)
        for file_path in files:
            audio = AudioSegment.from_file(file_path, format="wav")
            # pydub's .pan() expects a float in [-1.0, 1.0]
            panned_audio = audio.pan(pan_value)
            panned_file_path = file_path.replace(".wav", "_panned.wav")
            panned_audio.export(panned_file_path, format="wav")
            panned_category_files.append(panned_file_path)
        panned_files[category] = panned_category_files
    return panned_files

def apply_reverb(uploaded_files, reverb_settings):
    """
    Dynamically apply a subtle reverb effect by blending the original (dry)
    audio with a "wet" signal. The wet signal is generated by overlaying a few
    delayed copies of the original with exponential decay and then softened via a low-pass filter.

    reverb_settings:
      - delay: base delay in milliseconds between echoes.
      - pre_delay: additional initial delay before echoes start.
      - decay: dB attenuation per echo repeat.
      - repeats: number of delayed copies.
      - mix: wet/dry mix percentage (0 to 100). 0 means fully dry, 100 fully wet.
      - width: stereo spread for the reverb effect (0.0 = mono, 1.0 = full spread).
    """
    reverb_files = {}
    delay = reverb_settings['delay']
    pre_delay = reverb_settings.get('pre_delay', 0)  # New parameter for pre-delay
    decay = reverb_settings['decay']
    repeats = reverb_settings['repeats']
    reverb_mix = reverb_settings['mix']
    reverb_width = reverb_settings.get('width', 0.0)  # New parameter for stereo width

    for category, files in uploaded_files.items():
        reverb_category_files = []
        for file_path in files:
            audio = AudioSegment.from_file(file_path, format="wav")
            # Prepare a silent segment long enough to accommodate the echoes.
            wet_duration = len(audio) + pre_delay + delay * repeats
            wet_audio = AudioSegment.silent(duration=wet_duration)
            # Overlay a few echoes with exponential decay.
            for i in range(1, repeats + 1):
                # Apply a decay of (decay * i) dB to each echo.
                echo = audio.apply_gain(-decay * i)
                # Calculate the total delay for this echo (pre_delay + incremental delay)
                total_delay = pre_delay + delay * i
                # If reverb_width is greater than 0, create stereo echoes.
                if reverb_width > 0:
                    echo_left = echo.pan(-reverb_width)
                    echo_right = echo.pan(reverb_width)
                    delayed_left = AudioSegment.silent(duration=total_delay) + echo_left
                    delayed_right = AudioSegment.silent(duration=total_delay) + echo_right
                    wet_audio = wet_audio.overlay(delayed_left).overlay(delayed_right)
                else:
                    delayed = AudioSegment.silent(duration=total_delay) + echo
                    wet_audio = wet_audio.overlay(delayed)
            # Soften the wet signal with a low-pass filter.
            wet_audio = wet_audio.low_pass_filter(8000)
            
            # Blend dry and wet signals based on the mix ratio.
            if reverb_mix == 0:
                final_audio = audio
            elif reverb_mix == 100:
                final_audio = wet_audio
            else:
                dry_scale = (100 - reverb_mix) / 100.0
                wet_scale = reverb_mix / 100.0
                dry_gain = 20 * math.log10(dry_scale) if dry_scale > 0 else -120
                wet_gain = 20 * math.log10(wet_scale) if wet_scale > 0 else -120
                dry_audio = audio.apply_gain(dry_gain)
                wet_audio_scaled = wet_audio.apply_gain(wet_gain)
                final_audio = dry_audio.overlay(wet_audio_scaled)
            
            reverb_file_path = file_path.replace(".wav", "_reverb.wav")
            final_audio.export(reverb_file_path, format="wav")
            reverb_category_files.append(reverb_file_path)
        reverb_files[category] = reverb_category_files
    return reverb_files

def combine_processed_tracks(processed_files, output_filename="final_mix.wav"):
    """
    Combine (overlay) all processed/panned/reverbed tracks into one final stereo mix.
    """
    final_mix = None
    for category, files in processed_files.items():
        for file_path in files:
            track = AudioSegment.from_file(file_path, format="wav")
            if final_mix is None:
                final_mix = track
            else:
                # Overlay the track on top of the existing mix.
                final_mix = final_mix.overlay(track)
    if final_mix:
        final_mix.export(output_filename, format="wav")
        return output_filename
    return None

def main():
    st.title("KUYAM.io - Track Input Management")

    st.markdown("""
    **Welcome to KUYAM.io!** Upload your multi-track WAV files for automated mixing and mastering.

    ### Instructions:
    1. Upload the following tracks in WAV format:
        - **Vocals**: Lead and backing vocal tracks.
        - **Homophonic Instruments**: Rhythm guitars (up to 2), keyboards/piano (up to 2).
        - **Low-Frequency Instruments**: Bass.
        - **Drums/Rhythmic Tracks**: Kick, snare, cymbals.
        - **Lead Instruments**: Lead guitar or synth lead.
    2. Adjust the sliders to modify compression, volume, EQ, panning, reverb, and multi-pass filter settings.
    3. Process the tracks to apply the settings.
    """)

    # -- Compression --
    compression_ratio = st.slider("Set compression threshold (dB):", min_value=-60, max_value=0, value=-20)

    # -- Volume Balancing --
    volume_adjustments = {
        "Vocals": st.slider("Vocals Volume Adjustment (dB):", -10, 10, 5),
        "Lead Instruments": st.slider("Lead Instruments Volume Adjustment (dB):", -10, 10, 3),
        "Drums/Rhythmic Tracks": st.slider("Drums Volume Adjustment (dB):", -10, 10, -2),
        "Low-Frequency Instruments": st.slider("Bass Volume Adjustment (dB):", -10, 10, 1),
        "Homophonic Instruments": st.slider("Homophonic Instruments Volume Adjustment (dB):", -10, 10, 0),
    }

    # -- Equalization --
    eq_settings = {
        "Vocals": {
            'low_pass': st.slider("Vocals Low Pass Filter (Hz):", 1000, 20000, 8000),
            'high_pass': st.slider("Vocals High Pass Filter (Hz):", 20, 1000, 300)
        },
        "Lead Instruments": {
            'low_pass': st.slider("Lead Instruments Low Pass Filter (Hz):", 1000, 20000, 7000),
            'high_pass': st.slider("Lead Instruments High Pass Filter (Hz):", 20, 1000, 500)
        },
        "Drums/Rhythmic Tracks": {
            'low_pass': st.slider("Drums Low Pass Filter (Hz):", 1000, 20000, 10000),
            'high_pass': st.slider("Drums High Pass Filter (Hz):", 20, 1000, 50)
        },
        "Low-Frequency Instruments": {
            'low_pass': st.slider("Bass Low Pass Filter (Hz):", 100, 1000, 300),
            'high_pass': st.slider("Bass High Pass Filter (Hz):", 20, 100, 20)
        },
        "Homophonic Instruments": {
            'low_pass': st.slider("Homophonic Low Pass Filter (Hz):", 1000, 20000, 10000),
            'high_pass': st.slider("Homophonic High Pass Filter (Hz):", 20, 1000, 100)
        },
    }

    # -- Panning --
    panning_settings = {
        "Vocals": st.slider("Vocals Panning (-1: Left, 0: Center, 1: Right):", -1.0, 1.0, 0.0),
        "Lead Instruments": st.slider("Lead Instruments Panning (-1: Left, 0: Center, 1: Right):", -1.0, 1.0, 0.0),
        "Drums/Rhythmic Tracks": st.slider("Drums Panning (-1: Left, 0: Center, 1: Right):", -1.0, 1.0, 0.0),
        "Low-Frequency Instruments": st.slider("Bass Panning (-1: Left, 0: Center, 1: Right):", -1.0, 1.0, 0.0),
        "Homophonic Instruments": st.slider("Homophonic Panning (-1: Left, 0: Center, 1: Right):", -1.0, 1.0, 0.0),
    }
    
    # -- Multi-Pass Filter Settings --
    multi_pass_count = st.slider("Multi-Pass Filter Count for Equalization:", min_value=1, max_value=5, value=1,
                                 help="Number of times the low-pass and high-pass filters are applied.")

    # -- Reverb Settings (Dynamic, Subtle) --
    reverb_delay = st.slider("Reverb Base Delay (ms):", 50, 500, 100,
                             help="Base delay in milliseconds between echoes.")
    # New slider: Reverb Pre-Delay
    reverb_pre_delay = st.slider("Reverb Pre-Delay (ms):", 0, 500, 50,
                             help="Initial delay before the first echo starts.")
    reverb_decay = st.slider("Reverb Decay (dB per echo):", 5, 20, 10,
                             help="Amount (in dB) to reduce each echo. Higher values yield a subtler reverb.")
    reverb_repeats = st.slider("Reverb Repeats:", 1, 5, 2,
                               help="Number of echoes to overlay.")
    reverb_mix = st.slider("Reverb Wet/Dry Mix (%):", 0, 100, 30,
                           help="Blend percentage: 0 = completely dry, 100 = completely wet.")
    # New slider: Reverb Width (Stereo Spread)
    reverb_width = st.slider("Reverb Width (Stereo Spread):", 0.0, 1.0, 0.5,
                             help="Stereo width of the reverb effect (0.0 = mono, 1.0 = full spread).")
    
    reverb_settings = {
        'delay': reverb_delay,
        'pre_delay': reverb_pre_delay,  # New parameter
        'decay': reverb_decay,
        'repeats': reverb_repeats,
        'mix': reverb_mix,
        'width': reverb_width           # New parameter
    }

    # -- File Upload Settings --
    track_categories = {
        "Vocals": ["vocals_lead", "vocals_back"],
        "Homophonic Instruments": ["rhythm_guitar_1", "rhythm_guitar_2", "keyboard_1", "keyboard_2"],
        "Low-Frequency Instruments": ["bass"],
        "Drums/Rhythmic Tracks": ["kick", "snare", "cymbals"],
        "Lead Instruments": ["lead_guitar_or_synth"],
    }

    uploaded_files = {}
    upload_path = "uploads"
    os.makedirs(upload_path, exist_ok=True)

    # Loop through categories and accept file uploads
    for category, file_tags in track_categories.items():
        st.subheader(category)
        category_files = []
        for tag in file_tags:
            uploaded_file = st.file_uploader(f"Upload {tag}.wav", type=["wav"], key=tag)
            if uploaded_file is not None:
                filepath = save_uploadedfile(uploaded_file, upload_path)
                category_files.append(filepath)
        if category_files:
            uploaded_files[category] = category_files

    # -- COMPRESSION --
    if st.button("Apply Compression"):
        if uploaded_files:
            compressed_files = apply_compression_to_all(uploaded_files, compression_ratio)
            st.write("### Compressed Tracks:")
            for category, files in compressed_files.items():
                st.write(f"**{category}:**")
                for file in files:
                    with open(file, "rb") as f:
                        st.download_button(label=f"Download {os.path.basename(file)}",
                                           data=f,
                                           file_name=os.path.basename(file))
        else:
            st.warning("No files uploaded yet.")

    # -- VOLUME BALANCING --
    if st.button("Apply Volume Balancing"):
        if uploaded_files:
            compressed_files = apply_compression_to_all(uploaded_files, compression_ratio)
            balanced_files = apply_volume_balancing(compressed_files, volume_adjustments)
            st.write("### Balanced Tracks:")
            for category, files in balanced_files.items():
                st.write(f"**{category}:**")
                for file in files:
                    with open(file, "rb") as f:
                        st.download_button(label=f"Download {os.path.basename(file)}",
                                           data=f,
                                           file_name=os.path.basename(file))
        else:
            st.warning("No files uploaded yet.")

    # -- EQUALIZATION --
    if st.button("Apply Equalization"):
        if uploaded_files:
            compressed_files = apply_compression_to_all(uploaded_files, compression_ratio)
            balanced_files = apply_volume_balancing(compressed_files, volume_adjustments)
            eq_files = apply_equalization(balanced_files, eq_settings, multi_pass_count)
            st.write("### Equalized Tracks:")
            for category, files in eq_files.items():
                st.write(f"**{category}:**")
                for file in files:
                    with open(file, "rb") as f:
                        st.download_button(label=f"Download {os.path.basename(file)}",
                                           data=f,
                                           file_name=os.path.basename(file))
        else:
            st.warning("No files uploaded yet.")

    # -- PANNING --
    if st.button("Apply Panning"):
        if uploaded_files:
            compressed_files = apply_compression_to_all(uploaded_files, compression_ratio)
            balanced_files = apply_volume_balancing(compressed_files, volume_adjustments)
            eq_files = apply_equalization(balanced_files, eq_settings, multi_pass_count)
            panned_files = apply_panning(eq_files, panning_settings)
            st.write("### Panned Tracks:")
            for category, files in panned_files.items():
                st.write(f"**{category}:**")
                for file in files:
                    with open(file, "rb") as f:
                        st.download_button(label=f"Download {os.path.basename(file)}",
                                           data=f,
                                           file_name=os.path.basename(file))
        else:
            st.warning("No files uploaded yet.")

    # -- REVERB (Dynamic, Subtle) --
    if st.button("Apply Reverb"):
        if uploaded_files:
            compressed_files = apply_compression_to_all(uploaded_files, compression_ratio)
            balanced_files = apply_volume_balancing(compressed_files, volume_adjustments)
            eq_files = apply_equalization(balanced_files, eq_settings, multi_pass_count)
            panned_files = apply_panning(eq_files, panning_settings)
            reverb_files = apply_reverb(panned_files, reverb_settings)
            st.write("### Reverb Tracks:")
            for category, files in reverb_files.items():
                st.write(f"**{category}:**")
                for file in files:
                    with open(file, "rb") as f:
                        st.download_button(label=f"Download {os.path.basename(file)}",
                                           data=f,
                                           file_name=os.path.basename(file))
        else:
            st.warning("No files uploaded yet.")

    # -- PROCESS ALL STEPS (FINAL) --
    if st.button("Process All Steps"):
        if uploaded_files:
            compressed_files = apply_compression_to_all(uploaded_files, compression_ratio)
            balanced_files = apply_volume_balancing(compressed_files, volume_adjustments)
            eq_files = apply_equalization(balanced_files, eq_settings, multi_pass_count)
            panned_files = apply_panning(eq_files, panning_settings)
            reverb_files = apply_reverb(panned_files, reverb_settings)

            st.write("### Processed Tracks (All Steps Applied):")
            for category, files in reverb_files.items():
                st.write(f"**{category}:**")
                for file in files:
                    with open(file, "rb") as f:
                        st.download_button(label=f"Download {os.path.basename(file)}",
                                           data=f,
                                           file_name=os.path.basename(file))

            # Create and provide a single final mix file
            final_mix_path = combine_processed_tracks(reverb_files, output_filename="final_mix.wav")
            if final_mix_path and os.path.exists(final_mix_path):
                with open(final_mix_path, "rb") as f:
                    st.download_button(label="Download Final Mixed Track",
                                       data=f,
                                       file_name=os.path.basename(final_mix_path))
        else:
            st.warning("No files uploaded yet.")

    st.markdown("---")
    st.markdown("Once all files are uploaded and processed, your final unified WAV can be downloaded above.")
    
if __name__ == "__main__":
    main()
